
version: '3.7'

services:
    web:
        build:
          context: ./
          dockerfile: Dockerfile
        command: >
          sh -c "python app.py"
        volumes:
        - .:/web
        ports:
        - '5000:5000'